/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    eleves: Eleve;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    eleves: ElevesSelect<false> | ElevesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'contact-page': ContactPage;
    'guestbook-page': GuestbookPage;
    'alumni-page': AlumniPage;
    'legal-notice-page': LegalNoticePage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'guestbook-page': GuestbookPageSelect<false> | GuestbookPageSelect<true>;
    'alumni-page': AlumniPageSelect<false> | AlumniPageSelect<true>;
    'legal-notice-page': LegalNoticePageSelect<false> | LegalNoticePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Comptes autorisés à modifier le contenu du site via cet espace d’administration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos et images utilisées sur le site (portrait, locaux, etc.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Courte description du contenu de l’image (accessibilité). Ex. : Nadia et Gilles Touché devant une batterie.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Fiches élèves optionnelles. L’identifiant URL est généré à partir du nom (/eleves/…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eleves".
 */
export interface Eleve {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Généré automatiquement à partir du nom (ex. Jean Dupont → jean-dupont). Videz le champ pour ne pas publier de page.
   */
  slug?: string | null;
  /**
   * Courte citation affichée sous le titre (optionnel).
   */
  quote?: string | null;
  photos?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex. : Batteur — groupe XYZ, professeur de batterie…
   */
  jobTitle?: string | null;
  /**
   * Un paragraphe par bloc, séparés par une ligne vide.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'eleves';
        value: string | Eleve;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eleves_select".
 */
export interface ElevesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  quote?: T;
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  jobTitle?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Coordonnées, réseaux sociaux et textes affichés dans l’en-tête et le pied de page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Forme abrégée du nom (ex. École de Batterie NGT). Utilisé dans l’en-tête, le pied de page et les titres de page.
   */
  schoolNameShort: string;
  /**
   * Affiché dans le pied de page, colonne Adresse.
   */
  addressStreet: string;
  addressCity: string;
  /**
   * Liste des téléphones affichés dans le pied de page.
   */
  phones?:
    | {
        /**
         * Optionnel. Ex. : Fixe, Mobile, Gilles…
         */
        label?: string | null;
        /**
         * Tel qu’affiché sur le site (ex. 04 42 63 03 74). Le lien d’appel est généré automatiquement.
         */
        number: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Toutes les adresses affichées dans le pied de page.
   */
  emails?:
    | {
        /**
         * Optionnel. Ex. : Contact général, Nadia, Gilles…
         */
        label?: string | null;
        address: string;
        id?: string | null;
      }[]
    | null;
  /**
   * URL complète de la page ou du profil (ex. https://instagram.com/…).
   */
  instagramUrl?: string | null;
  /**
   * URL complète de la page (ex. https://facebook.com/…).
   */
  facebookUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textes et photos des différentes sections affichées sur la page d’accueil du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  /**
   * Courte phrase en italique au-dessus du titre (ex. Écoute… et tu parviendras).
   */
  heroTagline: string;
  /**
   * Première ligne du titre (ex. École de Batterie).
   */
  heroName: string;
  /**
   * Deuxième ligne du titre, en italique (ex. Nadia & Gilles Touché).
   */
  heroSubtitle: string;
  /**
   * Affichée sous le titre (ex. Aix-en-Provence).
   */
  heroLocation: string;
  /**
   * Texte optionnel à côté de la ville (ex. Depuis 2003). Laisser vide pour ne rien afficher.
   */
  heroFounded?: string | null;
  /**
   * Libellé du bouton sous le titre (ex. Découvrir l’école). Le lien mène à la section « Pour qui ».
   */
  heroCta: string;
  /**
   * Citation entre guillemets, sans les « » (ajoutés automatiquement sur le site).
   */
  quoteText: string;
  /**
   * Nom affiché sous la citation (ex. Nadia et Gilles Touché).
   */
  quoteCite: string;
  /**
   * Portrait affiché à gauche de la citation. Créez d’abord le fichier dans Médias si besoin.
   */
  quotePortrait?: (string | null) | Media;
  /**
   * Court texte en majuscules au-dessus du titre (ex. Pour qui).
   */
  audienceLabel: string;
  /**
   * Grand titre visible sur la page d’accueil.
   */
  audienceTitle: string;
  audienceParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex. La pédagogie
   */
  pedagogyLabel: string;
  pedagogyTitle: string;
  /**
   * Texte d’introduction en tête de section, avant les autres paragraphes.
   */
  pedagogyLead: string;
  /**
   * Suite du texte de présentation, affichée sous le premier paragraphe.
   */
  pedagogyBody?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  courseOrganizationTitle: string;
  courseOrganizationItems?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Texte affiché sous la liste à puces.
   */
  courseOrganizationFooter: string;
  practiceTitle: string;
  practiceBody: string;
  intensiveCoursesTitle: string;
  intensiveCoursesParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Bouton en bas de l’encadré (ex. En savoir plus). Mène à la page Contact.
   */
  intensiveCoursesButtonLabel: string;
  /**
   * Ex. Les locaux
   */
  facilitiesLabel: string;
  facilitiesTitle: string;
  /**
   * Un ou plusieurs paragraphes au-dessus de la galerie photos.
   */
  facilitiesDescription?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Grille de photos en bas de section. La première peut être affichée en grand format.
   */
  facilitiesGallery?:
    | {
        image: string | Media;
        /**
         * Texte affiché au survol de la photo (optionnel).
         */
        caption?: string | null;
        /**
         * Cochez pour une image large sur deux colonnes (idéal pour la salle principale).
         */
        wide?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contenu affiché sur la page Contact : photos d’accès et carte Google Maps.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  accessGallery?:
    | {
        image: string | Media;
        /**
         * Ex. : Accès à l’école, Rue Rifle Rafle…
         */
        caption?: string | null;
        /**
         * Occupe toute la largeur de la grille (2 colonnes).
         */
        wide?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Collez le code iframe fourni par Google Maps (« Partager » → « Intégrer une carte »), ou uniquement l’URL src du iframe.
   */
  mapsEmbed?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Message des professeurs et témoignages affichés sur la page Livre d’or.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guestbook-page".
 */
export interface GuestbookPage {
  id: string;
  /**
   * Ex. : À Dante Agostini
   */
  letterTitle: string;
  /**
   * Saisissez un paragraphe par bloc, séparés par une ligne vide.
   */
  letterContent: string;
  /**
   * Affichée sous le message (ex. Nadia & Gilles Touché).
   */
  letterSignature: string;
  testimonials?:
    | {
        /**
         * Optionnel. Si la fiche a une page (/eleves/…), le nom de l’auteur devient un lien.
         */
        student?: (string | null) | Eleve;
        /**
         * Un témoignage long peut tenir sur plusieurs paragraphes : séparez-les par une ligne vide.
         */
        content: string;
        /**
         * Nom affiché sous le témoignage (ex. Marie D., parent d’élève).
         */
        author: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Texte d’introduction et liste des anciens élèves affichés sur la page dédiée.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni-page".
 */
export interface AlumniPage {
  id: string;
  /**
   * Un paragraphe par bloc, séparés par une ligne vide (ex. La musique est au-delà des mots…).
   */
  introText: string;
  alumniList?:
    | {
        /**
         * Liez une fiche Élève pour activer le lien vers la page dédiée (/eleves/…).
         */
        student?: (string | null) | Eleve;
        /**
         * Utilisé si aucune fiche n’est liée, ou si le nom doit différer de la fiche.
         */
        name?: string | null;
        /**
         * Chaque ligne : un projet, un groupe, un festival, une collaboration, etc.
         */
        projects?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Texte affiché sur la page Mentions légales du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-notice-page".
 */
export interface LegalNoticePage {
  id: string;
  /**
   * Rédigez le texte des mentions légales.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  schoolNameShort?: T;
  addressStreet?: T;
  addressCity?: T;
  phones?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        label?: T;
        address?: T;
        id?: T;
      };
  instagramUrl?: T;
  facebookUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTagline?: T;
  heroName?: T;
  heroSubtitle?: T;
  heroLocation?: T;
  heroFounded?: T;
  heroCta?: T;
  quoteText?: T;
  quoteCite?: T;
  quotePortrait?: T;
  audienceLabel?: T;
  audienceTitle?: T;
  audienceParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  pedagogyLabel?: T;
  pedagogyTitle?: T;
  pedagogyLead?: T;
  pedagogyBody?:
    | T
    | {
        text?: T;
        id?: T;
      };
  courseOrganizationTitle?: T;
  courseOrganizationItems?:
    | T
    | {
        text?: T;
        id?: T;
      };
  courseOrganizationFooter?: T;
  practiceTitle?: T;
  practiceBody?: T;
  intensiveCoursesTitle?: T;
  intensiveCoursesParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  intensiveCoursesButtonLabel?: T;
  facilitiesLabel?: T;
  facilitiesTitle?: T;
  facilitiesDescription?:
    | T
    | {
        text?: T;
        id?: T;
      };
  facilitiesGallery?:
    | T
    | {
        image?: T;
        caption?: T;
        wide?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  accessGallery?:
    | T
    | {
        image?: T;
        caption?: T;
        wide?: T;
        id?: T;
      };
  mapsEmbed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guestbook-page_select".
 */
export interface GuestbookPageSelect<T extends boolean = true> {
  letterTitle?: T;
  letterContent?: T;
  letterSignature?: T;
  testimonials?:
    | T
    | {
        student?: T;
        content?: T;
        author?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alumni-page_select".
 */
export interface AlumniPageSelect<T extends boolean = true> {
  introText?: T;
  alumniList?:
    | T
    | {
        student?: T;
        name?: T;
        projects?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-notice-page_select".
 */
export interface LegalNoticePageSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}